
# Please do the following after VM is booted up:
# ssh into vm >> vagrant ssh
# switch to jenkins user >> sudo -iu jenkins
# install git from homebrew >> brew install git
# update/create .zshrc to add path and save >> vi .zshrc >> export PATH="/usr/local/bin:$PATH"
# source .zshrc >> source ~/.zshrc
# logout from the vm

authorized_keys = ["ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHfJER+eGjDa0PCjN9V+VSYjMO9CiCkuTEi7w0Fio85PL/qBI67L3HmUkIFsIcA5fLiheClfeBvQPhojPpPrJSUD/3/iDgqLW/dWTQ64bpInuOCZJtZbSkVnbeVVyAxO7CF/0yh7W0NOg+IallnCimOEsDGhma686FYcvvOweCJ+w3bYA9fPwNGTBxsc++hTs/mR/WYehc1gECVZ1zE2EBNF+N9Uov+p+SuFkccpCVFM5tVzduNuQsWy6TRjoUK/q/P4BxhV8M/E2lbWK6SZ+ieOgQsC7UxBel5a6B7G//MqO4ZfHJEtpy5LuiuZMxjl/pdbfWlIwshjtnplH4BN35 jenkins@main",
                   "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+eE2iEP0XcVfCRlTPm/xrb6oTgv5iI8LQCz2JGwthLMW2sVxQyzaKAbqmdZJRsNqiuMerZ06xSurVLRPLEjHJmChT5wBX14sBRESwhCQ+SIByce05BZ8iKVphZdtmthAXBpQHS+JAIAyO3nk9dcbeZEy0vfCGLvVOtQ6/1MSxtMJ23ECvMYqBjRnPuvWlC70kmKhOe/bJgSgp+7JW/YXoX62BzQ8HO4e5e8QQy9QDY3uuQbKTCnoPqkat14ARRr/Q63JMGhe6jEQamNCSgYH/b13uc/4xDSMeTfUJes3kWO8J7REWmAoausZ+LPT9hUJF+5pzuh2V2VOY/0Ks40PX jenkins@admin1"]

Vagrant.configure(2) do |config|
  config.vm.provision "shell", privileged: true, inline: 'echo "*/10 * * * * sudo /usr/sbin/ntpdate -u 0.north-america.pool.ntp.org 1.north-america.pool.ntp.org 2.north-america.pool.ntp.org 3.north-america.pool.ntp.org" | crontab -'

  config.vm.synced_folder ".", "/vagrant", disabled: true

  [31842].each do |port|
    config.vm.define "osx-15-#{port}" do |node|
      node.vm.box = "macos-10.15"
      node.vm.network "forwarded_port", guest: 22, host: port

      node.vm.provider "virtualbox" do |vb|
        vb.name = "osx-15-#{port}"
        vb.cpus = 2
        vb.memory = "5120"
        # vb.linked_clone = true
        vb.customize 'pre-boot', ['modifyvm', :id, '--audio', 'none']
      end

      node.vm.provision "shell", privileged: false, inline: <<EOF
defaults -currentHost write com.apple.screensaver idleTime 0
sudo chown -R jenkins:jenkins /usr/local/bin /usr/local/include /usr/local/lib /usr/local/etc /usr/local/sbin /usr/local/var /usr/local/opt /usr/local/share /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks
sudo chown -R jenkins:jenkins /usr/local/var/homebrew
chmod u+w /usr/local/*
#brew update
EOF

      authorized_keys.each do |key|
        node.vm.provision "shell", inline: "echo \"#{key}\" >> /Users/jenkins/.ssh/authorized_keys"
      end
    end
  end
end
